var FlashCardCollection = new Array();
var FlashCardCollectionNames = new Array();

FlashCardCollectionNames[0] = 'Finnish Sentences (263)';
FlashCardCollection[0] = [
"これは何に使うのですか？\tMihin tätä käytetään?"
,"映画に行きませんか？\tMennäänkö leffaan?"
,"自己紹介から始めましょう。\tAloitetaan esittelemällä itsemme."
,"文章の構造を理解する為に、２つの質問を聞くことができる。\tLauserakenteen ymmärtämistä varten voidaan asettaa kaksi peruskysymystä."
,"パスポートを見せてください。\tSaanko nähdä passinne?"
,"私は観光中です。\tOlen lomamatkalla."
,"私は出張中です。\tOlen liikematkalla."
,"車をレンタルしたいです。\tHaluaisin vuokrata auton."
,"この熱さはもう我慢できない。\tEn enää kestä tätä kuumaa."
,"今日はレポートを完成させる時間がない。\tEn ehdi tänään tekemään raporttia valmiiksi."
,"念のためもう一枚撮ります。\tOtan varmuuden vuoksi vielä yhden kuvan."
,"(ホテルのチェックイン時に)部屋を予約してあります。\tOlen varannut täältä huoneen."
,"一人旅をしています。\tOlen matkalla yksin."
,"私は頭がおかしくなった。\tOlen seonnut."
,"私がそれを書きました。\tMinä kirjoitin sen."
,"ミニバーを使っていません。\tEn ole käyttänyt minibaaria."
,"私は出発するところです。\tOlen lähdössä."
,"また来ます。\tTulen uudelleen."
,"（プレゼントの）箱の中を見ていいですか？\tVoinko katsoa paketin sisään?"
,"私は仏教に興味があります。\tOlen kiinnostunut buddhalaisuudesta."
,"私は仕事に対して良い態度を身につけようとしている。\tYritän kehittää hyvän asenteen työhöni."
,"あなたのやっていることが何一つ理解できない。\tEn ymmärrä mitään siitä mitä teet."
,"良いことを思いついた。\tSain hyvän ajatuksen."
,"君の何を考えているのか分かる。\tTiedän, mitä ajattelet."
,"君が嘘つきだということを忘れていた。\tUnohdin että olet valehtelija."
,"金曜夜のショーを２席予約したいのですが。\tHaluaisin varata 2 paikkaa perjantai-illan näytökseen."
,"私は少なくとも週に１回はサウナに入ります。\tKäyn saunassa vähintään kerran viikossa."
,"あれを見せてもらえますか？\tSaisinko katsoa tuota?"
,"私は映画を観に行きます。\tMenen katsomaan leffan."
,"私も同じ考えです。\tOlen samaa mieltä."
,"（ファストフードなどで）持って帰ります。\tOtan mukaan."
,"私はフランス語を一度も勉強したことがない。\tEn koskaan opiskellut ranskaa."
,"私はフィンランド語を５ヶ月勉強している。（現在完了）\tOlen opiskellut suomea viisi kuukautta."
,"（店などで）それにします。\tOtan sen."
,"私はそれが好きではない。\tEn pidä siitä."
,"理由は言えません。\tEn voi kertoa syytä."
,"私には仕事が必要です。\tTarvitsen työtä."
,"（私には）テクニカルサポートが必要です。\tTarvitsen teknistä tukea."
,"知りません。\tEn tiedä."
,"私は疲れていました。\tOlin väsynyt."
,"この小包を送りたいです。\tHaluaisin lähettää tämän paketin."
,"理解してくれることを願っています。\tToivon että ymmärrät."
,"気分がすぐれません。\tEn voi hyvin."
,"あなたの言っている意味が分かりません。\tEn tiedä, mitä tarkoitat."
,"すぐ彼（女）に電話します。\tSoitan hänelle heti."
,"どうやったらそれ(現状)を変えられますか？\tMiten voisin muuttaa sen?"
,"買い物に行くのをお薦めします。\tSuosittelen ostoksille menoa."
,"あなたと話がしたいです。\tHaluaisin puhua kanssasi."
,"私は明確に話さなかった。\tEn puhunut selvästi."
,"試着しても良いですか？\tVoinko sovittaa?"
,"今月は（酒は）飲みません。\tEn juo tässä kuussa."
,"インターネットが魅力的すぎて、仕事ができない。\tEn hoida töitäni, koska internet on liian kiehtova."
,"あなたに一つ送ります。\tLähetän sinulle yhden."
,"(私は)夕方に戻ります。\tPalaan illalla."
,"あと２０パーセント（給料を）貰えますか？\tVoinko saada 20 prosenttia lisää?"
,"そこまで歩いて行けますか？\tVoinko sinne kävellä?"
,"週末は私は昼まで寝ています。\tViikonloppuna minä nukun keskipäivään asti."
,"（買い物中など）見てるだけです。\tVain katselen."
,"ここに私は住んでいます。\tTässä minä asun."
,"私は真剣です。\tOlen tosissani."
,"昨晩のことはあまりよく覚えていない。\tEn muista eilisillasta paljoa."
,"出口を探しています。\tEtsin uloskäyntiä."
,"セーターを取りに行きます。\tHaen puseroni."
,"こういうのが欲しいです。\tHaluaisin jotain tällaista"
,"毎日犬と散歩します。\tKävelen joka päivä koiran kanssa."
,"（ファストフードなどで）店内で食べます。\tSyön täällä."
,"(電話で)また後でかけます。\tSoitan myöhemmin uudelleen."
,"待っていただければ、彼（女）を連れてきます。\tJos odotatte, haen hänet."
,"朝から晩までYouTubeで面白いビデオを見た。\tKatselin hauskoja videoita Youtubesta aamusta iltaan."
,"私が言葉を言うので、最初に思いついた言葉を言って下さい。\tSanon sanan ja sinä sanot, mitä ensin tulee mieleen."
,"私ならそんなことは聞かなかった。\tMinä en olisi kysynyt tuota."
,"映画行く？\tLähdetkö elokuviin?"
,"あなたは間違っています。\tOlet väärässä."
,"絶対に間違いありませんか？\tOletko ehdottoman varma?"
,"大丈夫ですか？\tOletko kunnossa?"
,"まだアパートを探していますか？\tEtsitkö vielä kämppää?"
,"本当にそれをしたい？\tHaluatko varmasti tehdä sen?"
,"じゃあ自分が馬鹿だと言いたいの？\tYrität siis sanoa, että olet ääliö?"
,"もちろんあなたが一番の友達です。\tTotta kai olet paras ystäväni."
,"どうやって知ったのですか？\tKuinka tiesit?"
,"あなたはアルコールに強いですか？\tKestätkö hyvin alkoholia?"
,"あなたは朝何時に起きますか？\tMihin aikaan sinä nouset aamulla?"
,"どの国へ旅行したことがありますか？\tMissä maissa olet matkustanut?"
,"彼（女）のことをどう思いますか？\tMitä ajattelet hänestä?"
,"（相手の発言について）どういう意味ですか？\tMitä tarkoitat?"
,"あなたにアドバイスしても構いませんか？\tSallitko että annan sinulle neuvon?"
,"いつベッドに入るつもりですか？\tMilloin sinä aiot mennä nukkumaan?"
,"（あなたは）どこへ行くのですか？\tMinne sä menet?"
,"子供は私のパスポートに載っています。\tLapseni on merkitty minun passiini."
,"車がどこにも見当たらない。（車が走ってない）\tAutoja ei näy missään."
,"（信号待ちで）立って待っているのがバカらしく見える。\tTuntuu typerältä seistä odottamassa."
,"そこには人が多すぎる。\tSiellä on liikaa väkeä."
,"水にはあらゆる気味悪いゴミが浮いている。\tVedessä lilluu kaikenlaista inhottavaa töhkää."
,"起きてよかった(起きる価値があった)\tKannatti herätä."
,"英語の契約書ありますか？\tOnko teillä englanninkielistä sopimusta?"
,"そこにはより短い列があった。\tSiellä oli lyhyempi jono."
,"変な気分だ。\tMinusta tuntuu oudolta."
,"なぜ凧が上がらないのでしょう？\tMiksi leija ei lennä?"
,"彼はぎりぎり列車に間に合いました。\tHän ehti junaan viime hetkessä."
,"プロトタイプは完璧に安全です。\tPrototyyppi on täysin turvallinen."
,"彼（女）はタダで働いている。\tHän tekee työn ilmaiseksi."
,"(私たちには)子供が２人います。\tMeillä on kaksi lasta."
,"Kelaカードありますか？\tOnko Kela-korttia?"
,"いつ雪が降り始めますか？\tKoska alkaa sataa lunta?"
,"それは永遠（に終わらないこと）のように見えてきた。\tSe alkaa näyttää ikuisuudelta."
,"それは公平には見えません。\tSe ei kuulosta reilulta."
,"朝飯前です。\tSe on helppoa kuin heinänteko."
,"それはとても近くにある。\tSe on ihan lähellä."
,"それは大きなステップだ。\tSe on iso askel."
,"それは不可能です。\tSe on mahdotonta."
,"それはフィンランドの伝統の味です\tSe on perinteinen maku Suomesta."
,"それはあなたを良く見えさせる。\tSe saa sinut näyttämään hyvältä."
,"それはあなたがバカか嘘つきであることを意味する。\tSe tarkoittaa, että olet joko hullu tai valehtelija."
,"君がいない家に帰ってくるなんて変な気分だ。\tOn outoa tulla kotiin, kun et olekaan täällä."
,"少しおかしい\tOn vähän outoa."
,"ちょっと信じ難い。\tOn vähän vaikea uskoa."
,"電車を乗り換えないといけませんか？\tOnko minun vaihdettava junaa?"
,"（病み上がりの人に）もうよくなりましたか？\tOnko parempi olo jo?"
,"それはここから遠いですか？\tOnko se kaukana täältä?"
,"それは本当ですか？\tOnko se totta?"
,"洋服着てる？\tOnko sinulla yhtään vaatetta yllä?"
,"少し時間ありますか？\tOnko sulla hetki?"
,"もっと大きな／小さなサイズはありますか？\tOnko suurempaa/pienempää kokoa?"
,"蚊に刺された時の塗り薬はありますか？\tOnko teillä voidetta hyttysten puremiin?"
,"怖いですか？\tPelottaako sinua?"
,"お客様は常に正しい。\tAsiakas on aina oikeassa."
,"車のエンジンが止まってしまった。\tAuton moottori leikkasi kiinni."
,"見てられない！\tEi kestä katsoa!"
,"私の落ち度ではありません。\tEi minun vika."
,"どうってことありません\tEi se mitään."
,"どっちでもいい／関係ない／大して変わりない\tEi sillä ole väliä."
,"貴方が来るほどの価値はありません。\tEi sinun kannata tulla."
,"全然寂しくないの？\tEikö sinulle tule yhtään ikävä?"
,"私はもう物理的な世界には興味がない。\tFyysinen maailma ei enää kiinnosta minua."
,"バスはホテルまで迎えにきますか？\tHakeeko bussi meidät hotellilta?"
,"歯が痛いです。\tHammastani särkee."
,"彼は私が病気だと思っている。\tHän luulee, että olen sairas."
,"彼は幸せそうに見える。\tHän vaikuttaa iloiselta."
,"彼女は私を辞めさせようとしている。\tHän yrittää saada minut lähtemään."
,"彼（女）は３８度の熱があります。\tHänellä on kolmekymmentäkahdeksan astetta kuumetta."
,"彼（女）は持っているはずだ\tHänellä pitäisi olla."
,"こんなの馬鹿げてる。\tTämä on hullua."
,"これはあなたにも関係のあることです。\tTämä vaikuttaa myös sinuun."
,"無効手続はうまく行きましたか？\tSujuiko mitätöinti ihan hyvin?"
,"口約束は拘束力がある。\tSuullinen sopimus on sitova!"
,"愛が最も良い薬です。\tRakkaus on paras lääke."
,"食事の用意ができました。\tRuoka on valmista."
,"今日が私の最初の講義です。\tTänään on ensimmäinen luentoni."
,"目がしみる\tSilmiä kirvelee."
,"待つしかありません。\tTäytyy vain odottaa."
,"１時間が過ぎた。\tTunti päättyi."
,"セキュリティはユーザビリティーよりも大事だ。\tTurvallisuus on tärkeämpää kuin käytettävyys."
,"出口は左です。\tUloskäynti on vasemmalla."
,"普通のコーヒーでいいです。\tIhan tavallinen kahvi käy."
,"エレベータはこの廊下の突き当たりです。\tHissi on tämän käytävän päässä."
,"朝食が待っています。\tAamiainen odottaa."
,"それはそんな感じのものでした。\tJotain sellaista se oli."
,"全てつじつまが合う。\tKaikki täsmää."
,"礼拝堂の中は走ってはいけません。\tKappelissa ei saa juosta."
,"（取り寄せなどで）どのくらい（時間が）かかりますか？\tKauanko se kestää?"
,"誰がもう一つディスプレイをもらったんだ？\tKuka sai toisen näytön?"
,"よさそうですね！／いいですね！\tKuulostaa hyvältä!"
,"(電話で)聞きづらいです。\tKuuluu huonosti."
,"私たちにはプロジェクトを遂行するリソースがない。\tMeillä ei ole resursseja toteuttaa hanketta."
,"（子供に）大きくなったら何になりますか？\tMikä sinusta tulee isona?"
,"なぜ彼（女）は私をからかうの？\tMiksi hän kiusaa minua?"
,"私には１つしかないのになぜ彼（女）は２つモニタをもらったの？\tMiksi hän sai kaksi näyttöä kun minulla on vain yksi?"
,"何の音ですか？\tMikä ääni se on?"
,"それは何時に始まりますか？\tMihin aikaan se alkaa?"
,"ついさっきある人から貴方に電話がありました。\tJoku tyyppi soitti sinulle äsken."
,"もし彼（女）が私みたいな人間だったら、安心するだけだよ。\tJos hän on yhtään kuin minä, hän on vain helpottunut."
,"私に提案があります。\tMinulla on ehdotus."
,"私は花粉症です。\tMinulla on siitepölyallergia."
,"あなたに大事な話があります。\tMinulla on sinulle tärkeää asiaa."
,"私にとっては重要だったけど、あなたにとってはそうじゃないみたいね！\tMinulle se oli merkittävää, mutta ehkä ei sinulle!"
,"トイレに行かなくちゃ。\tMinun pitää mennä vessaan."
,"一番近いバス停はどこですか？\tMissä on lähin bussipysäkki?"
,"休暇はいつからですか？\tMistä alkaen on lomaa?"
,"どうすればそこに行けますか？\tMiten sinne pääsee?"
,"これはいくらですか？\tPaljonko tämä maksaa?"
,"まもなく雨になりそうだ。\tPian tulee vettä."
,"何が起きたのですか？\tMitä on tapahtunut?"
,"郵便局はあそこです。\tPosti on tuolla."
,"大統領は辞めざるをえなかった。\tPresidentti joutui eroamaan."
,"電話が壊れた\tPuhelin meni rikki."
,"まったく意味を成しません。\tSiinä ei olisi tolkkua."
,"一体なんだろう？\tMitä se voisi olla?"
,"休暇はどうでしたか？\tMillainen lomasi oli?"
,"彼（女）はいつ帰ってきますか？\tMilloin hän palaa?"
,"プロジェクトのステータスレポートはいつできますか？\tMilloin hankkeesi tilanneraportti on valmis?"
,"それはどのように聞こえますか？\tMiltä se kuulostaa?"
,"私たちはいつも会っている。\tMe näemme toisiamme koko ajan."
,"私たちはこれについて最後まで考えなかった。\tEmme ajatelleet tätä loppuun asti."
,"そしたら私たちは映画に間に合わなくなってしまう。\tSitten emme ehdi leffaan."
,"私たちはとても酔っ払っていた\tOlimme tosi kännissä."
,"じゃなかったらなぜ私たちがここにいましょうか。\tMiksi muuten olisimme täällä?"
,"なんで同じベッドで寝てるの？\tMiksi olemme samassa sängyssä?"
,"私の前の職場では全てをここよりうまくやっていた。\tEdellisessä työpaikassani teimme kaiken paremmin kuin täällä."
,"（歯医者で）麻酔をしてもらえますか？\tVoitteko antaa puudutuksen?"
,"私を助けてもらえますか？\tVoitteko auttaa minua?"
,"（買い物中など）何か他のものを見せて頂けますか？\tVoitteko näyttää jotain muita?"
,"書いていただけますか？\tVoisitteko kirjoittaa?"
,"バンクカード使えますか？\tHyväksyttekö pankkikortteja?"
,"（あなたたちは）何の話をしていたのですか？\tMistä te juttelitte?"
,"(あなたたちは)ここで何をしているのですか？\tMitä te teette täällä?"
,"この販売機の使い方を教えてください。\tNäytättekö, kuinka tämä automaatti toimii?"
,"たぶん、だからあなた達も来たのでしょう？\tSiksi kai tekin tulitte?"
,"みんな結婚するの？\tMenevätkö kaikki naimisiin?"
,"食器売場は何階ですか？\tMissä kerroksessa ovat astiat?"
,"写真はいつできますか？\tMilloin kuvat ovat valmiit?"
,"飲み込まないで下さい。\tÄlkää nielaisko."
,"これでうがいをしてください。\tKurlatkaa kurkkuanne täällä."
,"君も一緒においでよ！\tTule sinäkin mukaan!"
,"中に入って！\tTule sisään!"
,"戻ってきて！\tTule takaisin!"
,"待って！\tOdota!"
,"捕まえてみな！\tOta kiinni!"
,"落ち着きなさい。\tOta rennosti."
,"正当な理由がない限りタイヤの空気圧を下げてはいけません。\tÄlä ikinä laske renkaiden ilmanpainetta ilman pätevää syytä."
,"私にお礼はいりません。\tÄlä minua kiitä."
,"そのことは心配しないで。\tÄlä siitä huoli."
,"最後まで言わせて下さい。\tAnna minun puhua loppuun."
,"少なくとも月１回はタイヤの空気圧を点検しましょう。\tTarkista renkaiden ilmanpaine vähintään kerran kuukaudessa."
,"これらの修正をしてもう一度持ってきなさい。\tTee nämä muutokset ja tuo se minulle uudelleen."
,"(タクシーで)次の信号を渡ったところで停めて下さい。\tJättäkää minut seuraavien liikennevalojen jälkeen."
,"あなた自身のことを話しなさい。\tKerro itsestäsi."
,"間違っていたら言ってください。\tKorjaa jos sanoin väärin."
,"私の気が変わる前に行きなさい。\tMene nyt ennen kuin muutan mieleni."
,"彼（女）に会ったら、悪いニュースを伝えておいて。そうすれば私の（話）があまり悪く聞こえないから。\tJos näette häntä, kertokaa hänelle huono uutinen, jotta minun ei tunnu niin pahalta."
,"後でまた聞いて下さい。\tKysy myöhemmin uudelleen."
,"謝りなさい。\tPyydä anteeksi."
,"彼（女）にバカなことをやめるよう言いなさい。\tPyydä häntä lopettamaan typeryys."
,"多分、あとで。\tEhkä myöhemmin."
,"わざとじゃない。\tEi tarkoituksella."
,"グッジョブ！\tHieno homma!"
,"素晴らしい話だ。\tHieno juttu."
,"(ホテルのチェックイン時に)予約番号はこれです。\tTässä varausnumero."
,"急いで！\tVauhtia!"
,"冗談だよ！\tVitsi!"
,"残念！\tVoi harmi!"
,"なんてこった！\tVoi luoja!"
,"お帰りなさい！\tTervetuloa takaisin!"
,"（店を出るときなど）どうも！\tKiitos hei!"
,"（家に）来てくれてありがとう。\tKiitos vierailusta."
,"ご理解ありがとうございます。\tKiitos ymmärryksestä."
,"良いタイミングだ。\tHyvä ajoitus."
,"明日から来週の火曜日まで\tHuomisesta ensi viikon tiistaihin."
,"私が何か学ぶことのできる誰か\tJoku josta voisin oppia jotain."
,"本当ですか？？\tlhan tosi?"
,"素晴らしい！\tMahtavaa!"
,"（困っている人などに）どうしましたか？\tMikä hätänä?"
,"（ファストフードなどで）飲み物は何にしますか？\tMillä juomalla?"
,"遅れてすみません。\tAnteeksi että olen myöhässä."
,"私たちの専門学校に興味をもってくれて嬉しいです。\tHauskaa, että olet kiinnostunut ammattikorkeakoulustamme."
,"バカなことをしなくて良かった。\tHyvä ettei tehty typeryyksiä."
,"私の番です。\tMinun vuoroni."
,"私が覚えている限りは。\tMuistaakseni."
,"11時45分（12時15分前）\tNeljännestä vaille kaksitoista."
,"6時15分\tNeljännestä yli kuusi."
,"ちょっと待って下さい。\tPieni hetki."
,"（レジ待ちの列ができているときに、店員が隣のレジを開けて） 列の次の方どうぞ。\tSeuraava jonosta."
,"彼（女）に悪いニュースねぇ。。。\tHuono uutinen hänelle..."
,"完璧な日だ！\tTäydellinen päivä!!"
];

FlashCardCollectionNames[1] = 'Finnish Words (361)';
FlashCardCollection[1] = [
"64-bittinen\t64-bit (adjective)"
,"äänestää + 分格\tto vote for"
,"ääni\tsound, vote"
,"ahkera\tindustrious, hardworking"
,"aiempi\tearlier"
,"aikalisä\ttime-out"
,"alkava\tstarting"
,"alus\tcraft, ship"
,"alustava\ttentative"
,"arvioida\tto estimate"
,"asiantuntija\texpert"
,"avioero\ta divorce"
,"avioitua\tto get married"
,"avoimuus\tsincerity, openness"
,"biisi\t(colloquial) song"
,"Eduskunta\tthe Finnish parliament"
,"ei ... eikä ~\tneither ... or ~"
,"ei löytänyt\tdidn't find"
,"entisestään\tstill, even more"
,"epäillä\tto doubt, to question"
,"erottaa\tto separate"
,"esi-\tpre-"
,"esillä\tout (in the open), visible, showing"
,"esittää\tto express, submit, show"
,"esitys\tpresentation"
,"etsiä\tto search for"
,"etsiskellä\tto search"
,"euroalue\tEurozone (ユーロ圏)"
,"geeni\tgene"
,"haastaa\tto challenge"
,"häätää\t強制退去させる"
,"hajota\tto disperse, scatter, break up, run in all directions."
,"hajottaa\tto scatter, to break up, to dissolve"
,"hakemus\tapplication (written request)"
,"hallinto-oikeus\tthe (Finnish) administrative court"
,"hallita\tto rule, to control"
,"hallitus\tgovernment"
,"hämärä\tdusk, twilight"
,"harkitseva\tdeliberate"
,"hätäkokous\temergency meeting"
,"havainnollistaa\tto demonstrate"
,"hedelmällisyys\tfertility"
,"heikko\tweak"
,"helpottaa\tto make easier"
,"hieman\ta little"
,"hölmöys\tfoolishness"
,"hunaja\thoney"
,"huolto\tservice, maintenance"
,"hylätä\tto reject"
,"hyökkäys\tattack"
,"hyvinvointi\twell-being"
,"ihmetellä\tto wonder"
,"ikoni\ticon"
,"ilmaiseksi\tfor free"
,"innostua\tto get excited"
,"isäntä\tmaster, host"
,"iskeä\tto hit, strike"
,"isku\thit, blow, impact"
,"itsevarma\tself-confident"
,"jäädä kiinni\tto get/be caught"
,"jäädä mieleen\t心に残る"
,"jälleen\tagain"
,"järjestää \tto organize"
,"jättää\tto leave, to submit"
,"johto\tcord, administration"
,"jokin\tsomething"
,"julkisuus\tpublicity (広報)"
,"jumpata\tto exercise"
,"kaataa\tto pour, to spill, to shoot/kill down (game)"
,"kahdesti\ttwice"
,"kaide\trailing, handrail"
,"kaihi\t白内障"
,"kaivata + 分格\tto long for, to miss, to want"
,"kaksikko\tduet, duo, pair"
,"kannattaja\tsupporter, fan"
,"kasvattaa\tto grow, to raise, to increase"
,"kauan odotettu\t待望の"
,"kauhu\thorror"
,"kellottaa\tto clock, to time"
,"kenttä\tfield"
,"keskenään\tbetween each other, with each other"
,"KHO, Korkein hallinto-oikeus\tThe Supreme Administrative Court"
,"kierros\t(noun) round"
,"kiistely\twrangle (noun)"
,"kiittää\tto thank"
,"kirjain\ta character, letter"
,"kirjata\tto book, log"
,"kirjeenvaihtaja\tcorrespondent, 通信員、特派員"
,"kirjeenvaihto\tcorrespondence, 通信"
,"kirurginen\tsurgical"
,"kohdistus\tfocus"
,"kokea\tto experience"
,"kokoontua\tto gather"
,"kolmivuotias\t3 years old"
,"kompromissiehdotus\t妥協案"
,"kotiyleisö\thome supporters"
,"kriisi\tcrisis"
,"kuiskailla\tto whisper"
,"kukkaiskieli\tlanguage of flowers"
,"kulutus\tconsumption"
,"kumpikaan\teither, neither, not...either"
,"kurvi\tcurve"
,"kuulla\tto hear"
,"kuulustella\tto interrogate"
,"kyetä + 入格\tto be able to ~"
,"kysely\tinquiry"
,"lähellä + 分格\tnear ~"
,"lähes\talmost, nearly"
,"laina\tloan"
,"lainsäädäntö\tlegislation"
,"laittaa\tto put"
,"laittaa kohdistuksen\tto put focus"
,"laittomasti\tillegally"
,"lehti\tnewspaper, leaf"
,"levätä\tto rest, to take a break"
,"levitä\tto spread"
,"levittäjä\tdistributor"
,"lihavuus\t肥満"
,"liikenne\ttraffic"
,"liikkua\tto move, to travel"
,"liitto\tunion, marriage"
,"lisääntyä\tto reproduce"
,"lisääntyminen\treproduction"
,"loistohotelli\tluxury hotel"
,"lopputulos\t(final) result"
,"loukkaantua\tto be hurt/injured/wounded"
,"lukema\treading (a value indicated by a measuring device)"
,"lukuisa\tnumerous"
,"luonnollisesti\tnaturally"
,"lyödä\tto hit, to beat"
,"maali\tpaint, a goal"
,"maaliton\tpaintless, goalless"
,"maalivahti\tgoalkeeper"
,"maanantain vastaisena yönä\t(at) the night before Monday"
,"määräys\tspecification, instruction"
,"määritellä + 変格\tto define as ~"
,"mainita\tto mention"
,"marssi\tmarch"
,"matkustajakone\tpassenger plane"
,"mekanismi\tmechanism"
,"messu\tmass"
,"meteorologi\tmeteorologist"
,"miehistö\tcrew"
,"mielenosoittaja\tdemonstrator"
,"mielenosoitus\tdemonstration"
,"minimi\tminimum"
,"minimiveloitus\tminimum charge"
,"mittaus\tmeasurement"
,"murha\tmurder"
,"murhaoikeudenkäynti\tmurder case trial"
,"näpäyttää\tto click, flick"
,"näyttelyosuus\texhibition part"
,"niin sanottu\tso-called"
,"nivel\t関節"
,"nollaenergiatalo\tzero-energy building"
,"nopeus\tvelocity, speed"
,"nostaa\tto lift"
,"nousta tasoihin\t同点に追いつく"
,"nuoli\tarrow"
,"nykyihminen\tthe modern human"
,"odotus\twait, expectation"
,"ohjain\tcontroller, a piece of hardware"
,"oikeudenkäynti\ttrial"
,"oikeusministeriö\tthe Ministry of Justice"
,"olla odotettavissa\tto be expected"
,"olla olemassa\tto exist"
,"olla peräisin + 出格／離格\tto be original to, to originate from"
,"ollenkaan\t(否定文で) at all, never"
,"ongelmitta\twithout problems (ongelmaの複数欠格)"
,"osavaltio\t州"
,"osoittaa\tto show, to indicate"
,"osoittaa mieltä\tto demonstrate (to participate in a demonstration)"
,"ottaa käyttöön\tto put into use"
,"ottelu\t(sports) match"
,"päästä + 第三不定詞入格\tto manage (to do)"
,"päättää\tto decide, to conclude"
,"päättää\tto decide"
,"päättää + 不定詞\tto decide to (do sth)"
,"pahis\tbad guy"
,"painua\tto sink, to descend"
,"paremmin\tbetter (adverb)"
,"pärjätä\tto be fine, to be okay, to get along"
,"pehmittää\tto soften"
,"pelkkä\tmere"
,"penkki\tbench"
,"periaatteellinen\tprincipled, of principle"
,"periaatteessa\tbasically"
,"perinne\ttradition"
,"perinteiden mukaisesti\t伝統に従って"
,"persikka\tpeach"
,"piikki\ta spike"
,"pilkku\tcomma, dot"
,"poseerata\tto pose"
,"pronssi\tbronze"
,"prosessori\tprocessor, CPU"
,"puhumattakaan\tnot to mention, without speaking"
,"punnerrus\tpushup"
,"punnertaa\tto push up (weight lifting)"
,"puoliaika\ta half, as one of the 45-minute periods of a football game"
,"puolue\t(politics) a party"
,"purkaus\teruption (of a volcano)"
,"purku\tdemolition"
,"pusku\tヘディング"
,"puuhailla\tto keep busy with ..."
,"puute\tshortage, shortcoming"
,"puuttua + 入格\tto intervene, get involved with, interfere with"
,"pyrkiä\tto aspire, strive"
,"pystyä + 第三不定詞入格\tto be able to"
,"pysyvä\tpermanent"
,"rahoitus\tfinancing"
,"rajoittaa\tto restrict, to limit"
,"rangaistus\tpunishment"
,"rangaistuspilkku\tpenalty kick"
,"rankkari\tpenalty kick"
,"rattijuoppo\tdrunken driver"
,"reitti\troute"
,"riemuita\tto rejoice"
,"riippua + 出格\tto depend on ~"
,"riisua\tto undress"
,"rikollinen\tcriminal"
,"ristiriitainen\tcontradictory"
,"runsas\tabundant"
,"rytmi\trhythm"
,"saattaa + 不定詞\tto may (do something), to dare (to do something)"
,"sairaanhoito\thealth care"
,"sarja\tseries"
,"sarjakuvalehti\tcomic book"
,"sekä ... että ~\tboth ... and ~"
,"selain\tbrowser"
,"seteli\tbanknote, coupon"
,"seura\tcompany, society, association"
,"sievä\tcute, pretty"
,"sijasta\tinstead (of)"
,"sijoittaja\tinvestor"
,"sillä\tfor (理由を示す)"
,"sisäinen\tinternal"
,"sotkea\tto mess"
,"suhde\tproportion, ratio"
,"sulautettu\tembedded"
,"sulautettu tekniikka\tembedded technology"
,"Supo, Suojelupoliisi\tFinnish Security Police"
,"surma\ta violent death"
,"suunnitella\tto design, to plan"
,"suuri ero\tbig difference"
,"syntyä\tto be born"
,"syytetty\tthe accused, defendant"
,"syyttäjä\tprosecutor"
,"tahtoa\tto want"
,"taisto\tfight, battle"
,"tajuta\tto get the idea of something, to realize"
,"talouskriisi\teconomic crisis"
,"taltuttaa\tto tame"
,"tapa\tcustom, habit, manner, way"
,"taso\tlevel"
,"tausta\tbackground"
,"teho\tpower"
,"tekonivel\t人工関節"
,"tietokoneanimaatio\tcomputer animation"
,"tietokonepeli\tcomputer game"
,"tietoturva\tdata security"
,"tiettävästi\tas far as is known"
,"tiivistää\tto condense"
,"todeta\tto state"
,"toimenpide\toperation"
,"toimia ongelmitta\tto work with no problems"
,"toiminta\tactivity"
,"toiminto\tfeature"
,"toimittaja\treporter, journalist"
,"toisaalta\ton the other hand"
,"toistaiseksi\tso far, for the time being"
,"torjua\tto defend successfully, to turn down"
,"törmäys\timpact, crash"
,"tosin\talthough"
,"tuhkapilvi\tash cloud"
,"tulivuori\tvolcano"
,"tulos\tresult, profit, outcome"
,"tunnettu\tfamous, known"
,"tuoda\tto bring"
,"tuomio\tsentence, judgement"
,"tuore\tfresh, new, recent"
,"tutkinta\tinvestigation, hearing"
,"tuttu\tfamiliar"
,"tuttuun tapaan\tas usual"
,"tyhjä\tempty"
,"tyypillinen\ttypical"
,"uhri\tvictim"
,"ulkonaliikkumiskielto\tcurfew"
,"unioni\tunion"
,"upea\tgreat, gorgeous"
,"uudenlainen\tnovel"
,"uudistus\treform"
,"uutisoida\tto release a piece of news"
,"uutistoimisto\ta news agency"
,"vahvistaa\tto strengthen, to confirm"
,"vahvistus\tconsolidation, confirmation"
,"vaieta\tto fall silent, to keep silent"
,"vaihe\ta phase, stage, period"
,"vaikka\tfor example, although, even if"
,"vaikuttaa + 入格\tto affect ~, to concern ~"
,"väitellä\tto argue"
,"vakauttaa\tto stabilize"
,"vakava\tserious"
,"vakavasti\tseriously"
,"väki\tpeople"
,"väkivaltaisuus\tviolence"
,"valtaosa\tmajority, major part"
,"valtiovarainministeri\ta minister of finance"
,"valuutta\tcurrency"
,"vankila\tprison"
,"varoittaa\tto warn"
,"vartalo\tbody (as the physical structure of a human or an animal)"
,"vasta\tonly (not until, freshly)"
,"vastata + 分格\tto correspond to, to be similar to"
,"vei\tviedäの３人称単数過去形"
,"velka\tdebt"
,"veloitus\tcharge"
,"verkko\tnet, network, mesh"
,"vetää\tto pull"
,"viedä\tto take, to bring away"
,"vierailla\tto visit"
,"vihata\tto hate"
,"vihollinen\tan enemy"
,"viimeistellä\tto finnish (to apply a final treatment to)"
,"viisu\t(archaic) song"
,"viltti\tblanket"
,"virheellinen\terroneous"
,"virkistävä\trefreshing"
,"voitto\tvictory, win"
,"vuodenaika\tseason"
,"vyöhyke\tzone"
,"ydin\tcore, nucleus"
,"ydinvoimala\tnuclear power station"
,"yhdistää\tto connect, to join, to combine"
,"yhteisvaluutta\tcommon currency"
,"yhtiö\ta company"
,"ykköstapahtuma\tprime event"
,"yksipuolinen\tone-sided"
,"yläkulma\ttop corner"
,"ylimääräinen\tadditional, redundant, extra"
,"yllättävä\tsurprising"
,"yöllinen\tnocturnal, nightly"
,"出格 + lähtien\tas of, from ~ onwards"
,"分格 + vastaan\tagainst ~, towards ~"
,"属格 + aikaan\t～の頃は"
,"属格 + kuluessa\twithin ~"
,"属格 + lähellä\tnear ~"
,"属格 + luona\tat ~'s place"
,"属格 + mukaan\talong with ~, according to ~"
,"属格 + mukaisesti\tin accordance with ~"
,"属格 + on + 受動態現在分詞\t～しなければならない"
,"属格 + sijaan\tinstead of ~"
,"属格 + suhteen\tregarding ~"
,"属格 + vuoksi\tbecause of ~"
,"複数属格 + välillä\tbetween ~"
,"pudota + 出格\tto drop out of ~"
,"melkoinen\tquite a"
,"vuodesta toiseen\tyear in, year out / always"
,"kovin\tvery, really"
,"kuoro\tchoir"
,"toisin\totherwise, differently"
,"hirnahtaa\tto neigh shortly"
];

